# Generated by Django 5.1.2 on 2024-10-14 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('surname', models.CharField(help_text='Enter your surname.', max_length=100)),
                ('first_name', models.CharField(help_text='Enter your first name.', max_length=100)),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=100)),
                ('username', models.CharField(help_text='Enter a unique username.', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Enter your email address.', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter your phone number.', max_length=15)),
                ('role', models.CharField(help_text='Enter your role in the organization.', max_length=50)),
                ('organization', models.CharField(help_text='Enter the name of your organization.', max_length=100)),
                ('department', models.CharField(help_text='Enter your department.', max_length=100)),
                ('location', models.CharField(help_text='Enter your location.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
